; Script generated by Gemini CLI for Organizza Firma Stampa
; Implementation of Release Engineering Phase

[Setup]
AppId={{8A2B3C4D-5E6F-7G8H-9I0J-1K2L3M4N5O6P}
AppName=Organizza Firma Stampa
AppVersion=2.0.0
AppPublisher=COEMI
DefaultDirName={localappdata}\OrganizzaFirmaStampa
DefaultGroupName=Organizza Firma Stampa
AllowNoIcons=yes
OutputDir=.
OutputBaseFilename=OrganizzaFirmaStampa_Setup
Compression=lzma
SolidCompression=yes
PrivilegesRequired=lowest

[Languages]
Name: "italian"; MessagesFile: "compiler:Languages\Italian.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
; Copia tutti i file dalla cartella dist (generata da PyArmor)
Source: "dist\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
Name: "{group}\Organizza Firma Stampa"; Filename: "pythonw.exe"; Parameters: """{app}\main.py"""; WorkingDir: "{app}"
Name: "{commondesktop}\Organizza Firma Stampa"; Filename: "pythonw.exe"; Parameters: """{app}\main.py"""; WorkingDir: "{app}"; Tasks: desktopicon

[Run]
Description: "{cm:LaunchProgram,Organizza Firma Stampa}"; StatusMsg: "Avvio applicazione..."; Filename: "pythonw.exe"; Parameters: """{app}\main.py"""; WorkingDir: "{app}"; Flags: postinstall nowait skipifsilent
